---
# Playbook to deploy Ghost and its components

- name: Update hosts IP
  hosts: localhost
  become: yes
  roles:
    - kubernetes-cluster-ips

- name: Install and Config
  hosts: all
  become: yes
  gather_facts: false
  roles:
    - common

- name: Config Master
  hosts: master
  become: yes
  roles:
    - master