---

- name: Get node IP addresses
  shell: kubectl get nodes -o wide | awk '{print $6}' | tail -n +2
  register: node_ips

- name: Print node IP addresses
  debug:
    msg: "The IP address of node {{ node_ips.stdout_lines[0] }}"

- name: Set node IP address variables
  set_fact:
    node_ip_1: "{{ node_ips.stdout_lines[0] }}"
    node_ip_2: "{{ node_ips.stdout_lines[1] }}"
    
- name: Reescrever arquivo com variáveis
  template:
    src: hosts.j2
    dest: inventory/hosts.inv
    force: yes
