- name: GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install dependencies
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - containerd
    - ufw
    - net-tools

- name: Install Docker
  apt:
    name: docker.io
    state: latest
    force_apt_get: yes
    update_cache: yes

- name: Add line to daemon.json
  lineinfile:
    path: /etc/docker/daemon.json
    line: '{"exec-opts": ["native.cgroupdriver=systemd"]}'
    create: yes
  
- name: Activate docker
  service: 
    name: docker
    state: started
    enabled: yes

- name: Restart Docker
  shell: systemctl restart docker
  
- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet 
      - kubeadm 
      - kubectl

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a

- name: Verify kubelet
  service:
    name: kubelet
    state: started
    enabled: yes

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow